{{- /*
Licensed to the Apache Software Foundation (ASF) under one or more
contributor license agreements.  See the NOTICE file distributed with
this work for additional information regarding copyright ownership.
The ASF licenses this file to You under the Apache License, Version 2.0
(the "License"); you may not use this file except in compliance with
the License.  You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/ -}}

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "celeborn.master.statefulSetName" . }}
  labels:
    {{- include "celeborn.master.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "celeborn.master.serviceName" . }}
  selector:
    matchLabels:
      {{- include "celeborn.master.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "celeborn.master.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/tag: {{ .Values.image.tag | quote }}
      {{- with .Values.master.labels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.master.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.master.volumeMounts }}
      initContainers:
      - name: chown-celeborn-master-volume
        image: {{ include "celeborn.image" . }}
        {{- with .Values.image.pullPolicy }}
        imagePullPolicy: {{ . }}
        {{- end }}
        command:
        - chown
        - {{ .Values.master.securityContext.runAsUser | default 10006 }}:{{ .Values.master.securityContext.runAsGroup | default 10006 }}
        {{- range $volumeMount := .Values.master.volumeMounts }}
        - {{ $volumeMount.mountPath }}
        {{- end}}
        {{- with .Values.master.volumeMounts }}
        volumeMounts:
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.master.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        securityContext:
          runAsUser: 0
      {{- end }}
      containers:
      - name: celeborn-master
        image: {{ include "celeborn.image" . }}
        {{- with .Values.image.pullPolicy }}
        imagePullPolicy: {{ . }}
        {{- end }}
        command:
        - /usr/bin/tini
        - --
        - /bin/sh
        - -c
        {{- $namespace := .Release.Namespace }}
        - >
          until {{ range until (.Values.master.replicas | int) }}
          nslookup {{ include "celeborn.master.statefulSetName" $ }}-{{ . }}.{{ include "celeborn.master.serviceName" $ }}.{{ $namespace }}.svc.{{ $.Values.cluster.name }}.local &&
          {{- end }}
          true; do
            echo "waiting for master"; 
            sleep 2;
          done && exec /opt/celeborn/sbin/start-master.sh
        ports:
        - containerPort: {{ .Values.service.port }}
        - containerPort: {{ get .Values.celeborn "celeborn.master.http.port" | default 9098 }}
          name: metrics
          protocol: TCP
        {{- with .Values.master.env }}
        env:
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.master.envFrom }}
        envFrom:
        {{- toYaml . | nindent 8 }}
        {{- end }}
        volumeMounts:
        - name: {{ include "celeborn.fullname" . }}-volume
          mountPath: /opt/celeborn/conf
          readOnly: true
        {{- with .Values.master.volumeMounts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.master.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.master.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: {{ include "celeborn.fullname" . }}-volume
        configMap:
          name: {{ include "celeborn.configMapName" . }}
      {{- with .Values.master.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.master.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.master.tolerations }}
      tolerations:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- if or .Values.master.priorityClass.name .Values.master.priorityClass.create }}
      priorityClassName: {{ include "celeborn.master.priorityClassName" . }}
      {{- end }}
      terminationGracePeriodSeconds: 30
      {{- with .Values.master.dnsPolicy }}
      dnsPolicy: {{ . }}
      {{- end }}
      {{- with .Values.master.hostNetwork }}
      hostNetwork: {{ . }}
      {{- end }}
      {{- with .Values.master.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- with .Values.master.replicas }}
  replicas: {{ . }}
  {{- end }}
  {{- with .Values.master.volumeClaimTemplates }}
  volumeClaimTemplates:
  {{- toYaml . | nindent 2 }}
  {{- end }}
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
