apiVersion: v1
kind: Service
metadata:
  name: rss-worker-svc
  labels:
    {{- include "remote-shuffle-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  selector:
    {{- include "remote-shuffle-service.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/name: shuffleserviceworker
    app.kubernetes.io/role: worker
