# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Remote Shuffle Service CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_rss_on_spark:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java:
          - 8
        spark:
          - '2.4'
          - '3.0'
          - '3.1'
          - '3.2'
          - '3.3'
        hadoop:
          - '2.7'
          - '3.3'
    steps:
    - uses: actions/checkout@v2
    - name: Setup JDK ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: ${{ matrix.java }}
        cache: maven
        check-latest: false
    - name: Build with Maven
      run: build/mvn -Pspark-${{ matrix.spark }} -Plog4j-1 -Phadoop-${{ matrix.hadoop }} install -DskipTests
    - name: Check Java Code Style
      run: build/mvn -Pspark-${{ matrix.spark }} -Plog4j-1 -Phadoop-${{ matrix.hadoop }} checkstyle:check
    - name: Check Scale Code Style
      run: build/mvn -Pspark-${{ matrix.spark }} -Plog4j-1 -Phadoop-${{ matrix.hadoop }} scalastyle:check
    - name: Unit Test
      run: build/mvn -Pspark-${{ matrix.spark }} -Plog4j-1 -Phadoop-${{ matrix.hadoop }} test
